# Adapted from https://github.com/python-poetry/poetry/blob/master/.github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: flask-pg-session

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check Version
        id: check-version
        env:
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: |
          [[ v"$(poetry version --short)" = "$TAG_NAME" ]] \
            || (echo "version does not match tag" && exit 1)

      - name: Build project for distribution
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish -u __token__ -p $POETRY_PYPI_TOKEN_PYPI
